### ISSUE TITLE
openocd `reset run` does not work

### ISSUE THREAD

**Issue by benner** [Nuclei-Software/platform-nuclei#11]
By using provided `openocd` and configuration I cannot run targets (device is Longan Nano):

```
% % .platformio/packages/tool-openocd-nuclei/bin/openocd -f .platformio/packages/framework-nuclei-sdk/SoC/gd32vf103/Board/gd32vf103c_longan_nano/openocd_gd32vf103.cfg

% telnet 0 4444
Trying 0.0.0.0...
Connected to 0.
Escape character is '^]'.
Open On-Chip Debugger
> targets
    TargetName         Type       Endian TapName            State       
--  ------------------ ---------- ------ ------------------ ------------
 0* riscv.cpu          riscv      little riscv.cpu          halted

> reset run
JTAG tap: riscv.cpu tap/device found: 0x1e200a6d (mfg: 0x536 (Nuclei System Technology Co.,Ltd.), part: 0xe200, ver: 0x1)
JTAG tap: auto0.tap tap/device found: 0x790007a3 (mfg: 0x3d1 (GigaDevice Semiconductor (Beijing)), part: 0x9000, ver: 0x7)
Hart 0 didn't run coming out of reset in 1s; dmstatus=0x4303a2; Increase the timeout with riscv set_reset_timeout_sec.
> targets
    TargetName         Type       Endian TapName            State       
--  ------------------ ---------- ------ ------------------ ------------
 0* riscv.cpu          riscv      little riscv.cpu          halted
```

I found and adapted https://gist.github.com/elfmimi/1deb9c94b0f0900ae8a9df740b62bcd6 (added FTDI configuration) and it seems solves the problem.

**Comment by fanghuaqi** [comment]
I didn't have a longan nano board beside me, could you take a try with [nuclei-sdk](https://github.com/Nuclei-Software/nuclei-sdk/) here using latest [nuclei openocd](https://nucleisys.com/download.php).


In the latest nuclei-sdk, using this file https://github.com/Nuclei-Software/nuclei-sdk/blob/master/SoC/gd32vf103/Board/gd32vf103c_longan_nano/openocd_gd32vf103.cfg

Thanks
Huaqi

**Comment by benner** [comment]
Tried - same thing. Difference between platformio provided and current is only one line:

```
@@ -24,7 +24,7 @@
 transport select jtag
 
 set _CHIPNAME riscv
-jtag newtap $_CHIPNAME cpu -irlen 5
+jtag newtap $_CHIPNAME cpu -irlen 5 -expected-id 0x1e200a6d
 
 # Work-area is a space in RAM used for flash programming
 if { [info exists WORKAREASIZE] } {
```

**Comment by fanghuaqi** [comment]
@RomanBuchert Could you help to confirm on your loogan nano board using latest nuclei-sdk and nuclei openocd, @benner reported an issue for the openocd config file, but I didn't have a longan nano board on by hand. 

Thanks
Huaqi
