### ISSUE TITLE
Update GCC and SDK versions

### ISSUE THREAD

**Issue by gsauthof** [Nuclei-Software/platform-nuclei#12]
I'm using the nuclei-SDK with Platformio like this:

```
platform = nuclei
board = gd32vf103c_longan_nano
framework = nuclei-sdk
```

Currently, the environment pulls in [GCC 9.2.1](https://registry.platformio.org/tools/nuclei/toolchain-riscv-gcc-nuclei) which arguably is a bit outdated.

For example, it doesn't include `std::bit_cast()` and later versions have erroneous warnings fixed regarding enum class usage in bit-fields.

Of course, as always, more current GCC versions fix a lot of bugs, improve code generation and support newer language standards, in general.

Thus, my request: Could you update the Nuclei SDK/Platform on Platformio?

FWIW, I wouldn't mind SDK updates besides the GCC update, as well.

**Comment by fanghuaqi** [comment]
@gsauthof You can take a try with branch [feature/gd32vw55x](https://github.com/Nuclei-Software/platform-nuclei/tree/feature/gd32vw55x)

> This branch is still in development, may change in future.

> It use Nuclei Toolchain 2023.10 and OpenOCD 2023.10, integrated with Nuclei SDK 0.5.1 development version.

~~~shell
# in a pio shell and pwd is platform-nuclei
python3 .github/prepare_tools.py --pio
# above script will download required latest toolchain and nuclei sdk
# it will install required pio packages
~~~

Then you can develop offline using platformio 6.x now.

Sample workflow in github, see https://github.com/Nuclei-Software/platform-nuclei/actions/runs/7362396489/job/20040772564

![image](https://github.com/Nuclei-Software/platform-nuclei/assets/1538922/cde1a1e2-bcc6-4837-acfa-62aec92af0c2)
![image](https://github.com/Nuclei-Software/platform-nuclei/assets/1538922/c65209fd-6080-4e40-8562-7aa86215504b)
