### ISSUE TITLE
Uses unreleased packages

### ISSUE THREAD

**Issue by maxgerhardt** [Nuclei-Software/platform-nuclei#14]
The `platform.json` seems to refer to versions of PlatformIO registry packages that have not been uploaded yet or don't even exist yet.

```ps
PS C:\Users\Max\.platformio\platforms> pio pkg install -g -p "https://github.com/Nuclei-Software/platform-nuclei.git"
Platform Manager: Installing git+https://github.com/Nuclei-Software/platform-nuclei.git
git version 2.45.0.windows.1
Cloning into 'C:\Users\Max\.platformio\.cache\tmp\pkg-installing-i9xg05us'...
remote: Enumerating objects: 143, done.
remote: Counting objects: 100% (143/143), done.
remote: Compressing objects: 100% (119/119), done.
remote: Total 143 (delta 39), reused 50 (delta 12), pack-reused 0 (from 0)
Receiving objects: 100% (143/143), 165.47 KiB | 2.67 MiB/s, done.
Resolving deltas: 100% (39/39), done.
Platform Manager: nuclei@1.2.0+sha.8e8fffd has been installed!
Tool Manager: Installing toolchain-riscv-nuclei @ ~1.1.0
UnknownPackageError: Could not find the package with 'toolchain-riscv-nuclei @ ~1.1.0' requirements for your system 'windows_amd64'
```
`toolchain-riscv-nuclei` [does not exist](https://registry.platformio.org/search?q=toolchain-riscv-nuclei).

Similiarly 

https://github.com/Nuclei-Software/platform-nuclei/blob/8e8fffd2da5adc54bbd58b3f15795c7499d7ada2/platform.json#L40-L44

version 1.1.0 does not exist, only [0.10.1](https://registry.platformio.org/tools/nuclei/tool-openocd-nuclei/versions)

**Comment by maxgerhardt** [comment]
Nevermind, it's mentioned in the README to download the tools offline.. But, why-

**Comment by fanghuaqi** [comment]
> Nevermind, it's mentioned in the README to download the tools offline.. But, why-

Hi current master changes not support offline access see https://github.com/Nuclei-Software/platform-nuclei/blob/8e8fffd2da5adc54bbd58b3f15795c7499d7ada2/.github/workflows/build.yml#L32-L45, we didn't have budget to upload toolchain to pio package server, anyway, you can hack it via offline mode.
