### ISSUE TITLE
Board duplication with GigaDevice GD32V platform

### ISSUE THREAD

**Issue by valeros** [Nuclei-Software/platform-nuclei#3]
It's highly undesirable to have the same boards that are implemented in different platforms, for example, [gd32vf103v_eval](https://github.com/Nuclei-Software/platform-nuclei/blob/master/boards/gd32vf103v_eval.json) board is also present in [GigaDevice platform](https://github.com/sipeed/platform-gd32v/blob/master/boards/gd32vf103v-eval.json). 

Is it possible to have GigaDevice boards in the appropriate platform? For example you can create a PR with build script for your SDK so then users can simply use GigaDevice platform and specify your SDK as the framework.  Since the board IDs are different we can temporarily leave it how it is now, but it'd great if we could resolve in the proper way.

**Comment by fanghuaqi** [comment]
Thanks @valeros  for your suggestion, here are some concerns:
* Currently, we are using different board json file name and content, ours is `gd32vf103v_eval.json`, theirs is `gd32vf103v-eval.json`, we are using this `board.id` during build process to specify which `BOARD` we are build for using our `nuclei-sdk`, maybe in future, it is OK to update `gd32v` platform board json file to support `nuclei-sdk` framework, but I have concerns about copy examples code to `gd32v` platform.
* For `GD32V` based board, I would like to also have it in our platform support repo, so user of our Nuclei platform can also use this `gd32v` based boards.

**Comment by ivankravets** [comment]
https://github.com/Nuclei-Software/platform-nuclei/pull/6
