### ISSUE TITLE
CI failed due to nuclei sdk 0.2.6 package used

### ISSUE THREAD

**Issue by fanghuaqi** [Nuclei-Software/platform-nuclei#7]
Hi @ivankravets, 

I have updated framework-nuclei-sdk to 0.2.6, and put the package to https://github.com/Nuclei-Software/platform-nuclei/releases/tag/nuclei_tools_v0.1.0-alpha, but I see in commit https://github.com/Nuclei-Software/platform-nuclei/commit/14c3300a601ba3c60cf08c4bdaa0dc728d6e6a75, you introduced `"owner": "platformio",`, which seems that I need to upload package to `http://dl.platformio.org/packages`, but I don't have access to it.

![图片](https://user-images.githubusercontent.com/1538922/91930890-926d8000-ed14-11ea-8bd0-fc132d27a0f0.png)

Could you give me some hints for me how to upload package in your platformio server?

Thanks
Huaqi

**Comment by fanghuaqi** [comment]
Hi @ivankravets @valeros, could you help me to take a look at this issue, thanks in advance.

**Comment by ivankravets** [comment]
Hi 👋 

Could you restart CI builds? Does it work now?

**Comment by fanghuaqi** [comment]
Hi @ivankravets , I rebuild this commit, it works now.

I have a question, how can I upload a new package, I see in the latest commit, you have already deleted the maintained json files.

**Comment by ivankravets** [comment]
You did everything correctly. We moved all your packages from `platformio` to `nuclei` organization. Now you can maintain them personally. A few notes:

1. We updated manifests for your packages, added keywords, and other info. The upcoming front-end for the new PlatformIO Trusted Registry will use this info. So, before uploading the new `toolchain-riscv-gcc-nuclei` or `tool-openocd-nuclei`, please download the existing version from the registry and copy whole valuable meta information.

2. Please add a release tag in this repository and explain what was modified. See how [I did this for 1.0.9](https://github.com/Nuclei-Software/platform-nuclei/releases/tag/v1.0.9). I added `v1.0.9` tag and fill the rest info on github. Developers will see what was changed in dev-platform in PlatformIO IDE > PIO Home.

3. Please merge https://github.com/Nuclei-Software/nuclei-sdk/pull/5/files and re-publish the package again.

**Comment by fanghuaqi** [comment]
OK, got it. Thanks

**Comment by fanghuaqi** [comment]
Hi @ivankravets , I tried to use `pio package pack` command to package a new nuclei-sdk version, but it failed with the following issue, could you help with it, thanks

~~~
D:\workspace\Sourcecode\platform_storage\release>pio package pack d:\workspace\Sourcecode\nuclei-sdk-0.2.8.zip
Error: Invalid manifest fields: {'license': ['Could not load SPDX licenses for validation']}. 
Please check specification -> https://docs.platformio.org/page/librarymanager/config.html

D:\workspace\Sourcecode\platform_storage\release>pio package pack d:\workspace\Sourcecode\nuclei-sdk
Error: Invalid manifest fields: {'license': ['Could not load SPDX licenses for validation']}. 
Please check specification -> https://docs.platformio.org/page/librarymanager/config.html
~~~

Thanks
Huaqi

**Comment by fanghuaqi** [comment]
You can check with https://github.com/Nuclei-Software/nuclei-sdk/releases/tag/0.2.8

**Comment by ivankravets** [comment]
Is Github blocked in your country? Could you open this URL https://raw.githubusercontent.com/spdx/license-list-data/v3.10/json/licenses.json ?

**Comment by fanghuaqi** [comment]
I can access it using vpn, but without it, I can't.

**Comment by ivankravets** [comment]
I see. We moved SPDX licenses to Bintray https://github.com/platformio/platformio-core/commit/65b102921674d19dcb2e97ee9f9bf9ee9e5378cf

Could you re-run `pio upgrade --dev` and try again?

**Comment by fanghuaqi** [comment]
Sorry for late reply, I tried with this command, and it works, it worked.

~~~
(penv) D:\workspace\Sourcecode>pio package publish --owner nuclei framework-nuclei-sdk-0.2.8.tar.gz
The package has been accepted for moderation. We will notify you on email when process it.
~~~

Thanks
Huaqi
