### ISSUE TITLE
Latest platform-nuclei failed due to package not accepted

### ISSUE THREAD

**Issue by fanghuaqi** [Nuclei-Software/platform-nuclei#9]
Hi @ivankravets , I have use `pio package publish` published several new packages and update this repo, but I didn't receive any email about the package is accepted not processed, any way to know the progress, or I need to republish?

Thanks
Huaqi

**Comment by ivankravets** [comment]
Hi,

We have contacted you but didn’t receive any answer. Could you email me to me@ikravets.com or check your SPAM folder?

Thanks!

**Comment by fanghuaqi** [comment]
> Hi,
> 
> We have contacted you but didn’t receive any answer. Could you email me to [me@ikravets.com](mailto:me@ikravets.com) or check your SPAM folder?
> 
> Thanks!

Ok, just send email to you, using `fanghuaqi@vip.qq.com`, thanks.

**Comment by ivankravets** [comment]
There is no email. Could you contact us using our corporate form https://piolabs.com/company/about.html?

**Comment by fanghuaqi** [comment]
Done.
![image](https://user-images.githubusercontent.com/1538922/115985286-b5b7a900-a5dd-11eb-9e1b-aa355f437264.png)
